### ISSUE TITLE
read size exceeds bufferSize

### ISSUE THREAD

**Issue by bradisbell** [siphontv/webm-byte-stream#3]
I have on a couple occasions received the following error:

https://github.com/eadle/webm-byte-stream/blob/master/lib/webm-byte-stream.js#L220

> Error: read size exceeds bufferSize
    at WebMByteStream._read (node_modules\webm-byte-stream\lib\webm-byte-stream.js:220:11)
    at EbmlDecoder.<anonymous> (node_modules\webm-byte-stream\lib\webm-byte-stream.js:93:34)
    at emitOne (events.js:96:13)
    at EbmlDecoder.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at EbmlDecoder.Readable.push (_stream_readable.js:134:10)
    at EbmlDecoder.Transform.push (_stream_transform.js:128:32)
    at EbmlDecoder.readContent (node_modules\ebml\lib\ebml\decoder.js:166:14)
    at EbmlDecoder._transform (node_modules\ebml\lib\ebml\decoder.js:41:52)
    at EbmlDecoder.Transform._read (_stream_transform.js:167:10)
    at EbmlDecoder.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:333:12)
    at writeOrBuffer (_stream_writable.js:319:5)

I don't know the conditions to reproduce it.  Any suggestions for resolving this problem?  Any way to handle stream errors like this and close the stream gracefully?

**Comment by eadle** [comment]
The default buffer is 10MB. You can set a larger buffer size as one of the options or fork and use dynamic memory. It's literally just a buffer that loops on itself.

// default buffer size is 10 * 1024 * 1024 or 10MB
var webmstream = new WebMByteStream({bufferSize: 20 * 1024 * 1024}); // now 20MB

**Comment by bradisbell** [comment]
Thank you.  And, is there a way to handle the error?

**Comment by eadle** [comment]
The error occurs when a the cluster end  tag is encountered and the length of the cluster exceeds the buffer size. I pretty much forget everything about node and webm, sorry.
